name: Frontend Deploy

on:
  push:
    branches:
      - main  # main 브랜치에 push되면 실행

jobs:
  deploy:
    runs-on: ubuntu-latest  # 최신 우분투 환경에서 실행

    steps:
    - name: Checkout
      uses: actions/checkout@v2  # v2를 사용하는 것이 좋습니다.

    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # 프로젝트에 맞는 Node.js 버전을 지정하세요.

    - name: Install dependencies
      run: npm install  # 의존성 설치

    - name: Build
      run: npm run build  # 빌드 실행

    - name: Deploy to S3
      run: aws s3 sync ./build s3://your-s3-bucket-name  # S3 버킷으로 동기화
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
